
import formdata.absensi;
import formdata.alatGym;
import formdata.instruktur;
import formdata.karyawan;
import formdata.member;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author afgha
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mMember = new javax.swing.JMenuItem();
        mKaryawan = new javax.swing.JMenuItem();
        mAlatGym = new javax.swing.JMenuItem();
        mInstruktur = new javax.swing.JMenuItem();
        mAbsensi = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("SISTEM INFORMASI MEMBERSHIP GYM");

        jMenu1.setText("Master");

        mMember.setText("Member");
        mMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMemberActionPerformed(evt);
            }
        });
        jMenu1.add(mMember);

        mKaryawan.setText("Karyawan");
        mKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKaryawanActionPerformed(evt);
            }
        });
        jMenu1.add(mKaryawan);

        mAlatGym.setText("Alat Gym");
        mAlatGym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAlatGymActionPerformed(evt);
            }
        });
        jMenu1.add(mAlatGym);

        mInstruktur.setText("Instruktur");
        mInstruktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mInstrukturActionPerformed(evt);
            }
        });
        jMenu1.add(mInstruktur);

        mAbsensi.setText("Absensi");
        mAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAbsensiActionPerformed(evt);
            }
        });
        jMenu1.add(mAbsensi);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Report");

        jMenuItem6.setText("Member");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Karyawan");
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Alat Gym");
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Instruktur");
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Absensi");
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Logout");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Exit");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMemberActionPerformed
        member member = new member();
        member.setVisible(true);
    }//GEN-LAST:event_mMemberActionPerformed

    private void mAlatGymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAlatGymActionPerformed
      alatGym alatgym = new alatGym();
      alatgym.setVisible(true);
    }//GEN-LAST:event_mAlatGymActionPerformed

    private void mKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKaryawanActionPerformed
        karyawan karyawan = new karyawan();
        karyawan.setVisible(true);
    }//GEN-LAST:event_mKaryawanActionPerformed

    private void mInstrukturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mInstrukturActionPerformed
       instruktur ins = new instruktur();
       ins.setVisible(true);
    }//GEN-LAST:event_mInstrukturActionPerformed

    private void mAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAbsensiActionPerformed
        absensi abs = new absensi();
        abs.setVisible(true);
    }//GEN-LAST:event_mAbsensiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem mAbsensi;
    private javax.swing.JMenuItem mAlatGym;
    private javax.swing.JMenuItem mInstruktur;
    private javax.swing.JMenuItem mKaryawan;
    private javax.swing.JMenuItem mMember;
    // End of variables declaration//GEN-END:variables
}
